Revert "Reland "tast: add flag -companionduts and new API testing.State.CompDUTs""
This reverts commit 3e421848c001003a2f9f039a086628aacdcf7f6c.

Reason for revert: causes post-submit builders failures:

tast-local-tests-cros-0.0.1-r5659: --- FAIL: TestLocalSuccess (0.32s)
tast-local-tests-cros-0.0.1-r5659:     local_test.go:74: runLocalTest failed: failed to connect to 127.0.0.1:42637: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
tast-local-tests-cros-0.0.1-r5659: 2021/03/24 08:38:03 Got error while handling connection: failed to handshake: [ssh: no auth passed yet, unknown public key for "root"]
tast-local-tests-cros-0.0.1-r5659: FAIL


Original change's description:
> Reland "tast: add flag -companionduts and new API testing.State.CompDUTs"
>
> This is a reland of 86c042d04f1789c9ed1d272b39c92b13519ea0c4
>
> Original change's description:
> > tast: add flag -companionduts and new API testing.State.CompDUTs
> >
> > This CL is the first in a series to support companion DUTs. It only
> > added a new on command for user to specify companion DUTs and a new API
> > in testing.State for test access the companion DUTs.
> >
> > BUG=chromium:1185396
> > TEST=fast_build.sh -T; tast run -build=true -companiondut=cd1:octopus -companiondut=dut2:127.0.0.1:2225 hana meta.CompanionDUT
> >
> > Change-Id: I06109a03eff0e2dd6959c9922872bdd2e560ec01
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast/+/2753451
> > Tested-by: Seewai Fu <seewaifu@google.com>
> > Reviewed-by: Tatsuhisa Yamaguchi <yamaguchi@chromium.org>
> > Reviewed-by: Shuhei Takahashi <nya@chromium.org>
> > Commit-Queue: Seewai Fu <seewaifu@google.com>
>
> Bug: chromium:1185396
> Change-Id: I610168e10bb54394103964c9c3df629a82a9e70b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast/+/2782242
> Tested-by: Seewai Fu <seewaifu@google.com>
> Reviewed-by: Shuhei Takahashi <nya@chromium.org>
> Commit-Queue: Seewai Fu <seewaifu@google.com>

Bug: chromium:1185396
Change-Id: I4b376841b541d8bac722479e43c28d4038ce1447