Use the new logging mechanism in Tast CLI
This patch updates Tast CLI to consistently use the new logging
mechanism.

This patch makes almost no change to the current behavior with one
exception: now log files always contain debug logs even if -verbose
command line flag is not set. This is because the new logging mechanism
allows setting logging level per logger, and it makes not much sense
to use the same logging level for the console logger and file output
loggers.

BUG=b:192639665
BUG=b:187793617
TEST=fast_build.sh -T

Change-Id: Ifb1becaf7e047add7afaec955d651551d12801d9