tast: Use protocmp.Transform() in tests.
- Needed to uprev github.com/golang/protobuf to 1.5.2, see
crrev.com/3221333. The newer version of protobuf causes errors
such as

```
tast-local-tests-cros-0.0.2-r8048: --- FAIL: TestTestServerListEntitiesRecursive (0.80s)
tast-local-tests-cros-0.0.2-r8048: panic: cannot handle unexported field: Sort({*protocol.ListEntitiesResponse}.Entities)[2].Entity.LegacyData.Timeout.state
tast-local-tests-cros-0.0.2-r8048: consider using AllowUnexported or cmpopts.IgnoreUnexported [recovered]
tast-local-tests-cros-0.0.2-r8048: 	panic: cannot handle unexported field: Sort({*protocol.ListEntitiesResponse}.Entities)[2].Entity.LegacyData.Timeout.state
tast-local-tests-cros-0.0.2-r8048: consider using AllowUnexported or cmpopts.IgnoreUnexported
...
tast-local-tests-cros-0.0.2-r8048: chromiumos/tast/internal/bundle_test.TestTestServerListEntitiesRecursive(0xc000461680)
tast-local-tests-cros-0.0.2-r8048: 	/build/amd64-generic/tmp/portage/chromeos-base/tast-local-tests-cros-0.0.2-r8048/work/tast-local-tests-cros-0.0.2/tast-base/src/chromiumos/tast/internal/bundle/service_test.go:184 +0xe59
```

(see
https://ci.chromium.org/ui/p/chromeos/builders/cq/amd64-generic-cq/b8832787957957496353)

BUG=b:182898188
TEST=`emerge-amd64-generic tast-local-tests-cros`
TEST=CQ

Change-Id: I66ac50c0710fe9610feb7a8b7e0f1b9fed88ba75
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast/+/3228817
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Tested-by: Andrew Lamb <andrewlamb@chromium.org>
Commit-Queue: Andrew Lamb <andrewlamb@chromium.org>