Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8849951983924680480
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/testing/hwdep/hwdep.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/testing/hwdep/hwdep.go' with conflicts.
        U src/chromiumos/tast/testing/hwdep/hwdep.go

Patch-set: 4
Tag: autogenerated:cq:full-run