Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8870901269297580832
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: docs/test_dependencies.md:1
        Falling back to three-way merge...
        Applied patch to 'docs/test_dependencies.md' cleanly.
        error: patch failed: src/chromiumos/tast/cmd/local_test_runner/main.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/cmd/local_test_runner/main.go' with conflicts.
        U src/chromiumos/tast/cmd/local_test_runner/main.go

Patch-set: 3
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1135824 \u003c1135824@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"Someone else replied on the change"}