Revert "tast: label precondition errors"
This reverts commit 49ff1b981e06a3526d088fdb26a6a4639630adc5.

Reason for revert: Unittest is broken, but chumped.

--- FAIL: TestReportErrorInPrecondition (0.00s)
    state_test.go:195: Second line of stack trace "[Precondition failure] error 1\n\tat chromiumos/tast/testing.TestReportErrorInPrecondition (state_test.go:162)\n\tat testing.tRunner (testing.go:909)\n\tat runtime.goexit (asm_amd64.s:1357)" doesn't match "\tat chromiumos/tast/testing.TestReportErrorInPre (state_test.go:162)"
    state_test.go:195: Second line of stack trace "[Precondition failure] error 2\n\tat chromiumos/tast/testing.TestReportErrorInPrecondition (state_test.go:163)\n\tat testing.tRunner (testing.go:909)\n\tat runtime.goexit (asm_amd64.s:1357)" doesn't match "\tat chromiumos/tast/testing.TestReportErrorInPre (state_test.go:163)"

Original change's description:
> tast: label precondition errors
> 
> Whenever s.Error, s.Errorf, s.Fatal, or s.Fatalf are call during a
> precondition, "[Precondition failure] " is prepended to the log.
> 
> TEST=Added s.Error/Fatal/... to arc pre.go and ran tast run <eve>
> arc.UIAutomator
> BUG=chromium:1042822
> 
> Change-Id: Id6d26f147edc6b55e54bcc0aa91e21d2f9afa344
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast/+/2015816
> Tested-by: Brendan Hansknecht <bhansknecht@chromium.org>
> Reviewed-by: Shuhei Takahashi <nya@chromium.org>

Bug: chromium:1042822
Change-Id: I9b22842e38c8aa729f51338f30302ecef40abbcf