Revert "tast: Introduce testing.TestHookState."
This reverts commit a522262d3b26e29880e38919868092777a40a787.

Reason for revert: ToT build breakage.
tast-cmd-0.0.1-r725: src/chromiumos/tast/internal/testing/state.go:213:18: not enough arguments in call to NewContext
tast-cmd-0.0.1-r725: 	have (context.Context, *TestHookState)
tast-cmd-0.0.1-r725: 	want (context.Context, *TestContext, func(string))
Looks conflicting with crrev.com/c/2275386

Also, just fixing the line 213 does not fix the problem. I still hit another build error on bundlemain package.

../platform/tast-tests/src/chromiumos/tast/local/bundlemain/main.go:158:3: cannot use testHook (type func(context.Context, *"chromiumos/tast/internal/testing".State) func(context.Context, *"chromiumos/tast/internal/testing".State)) as type func(context.Context, *"chromiumos/tast/internal/testing".TestHookState) func(context.Context, *"chromiumos/tast/internal/testing".TestHookState) in field value

Original change's description:
> tast: Introduce testing.TestHookState.
> 
> We want to provide a few more methods to test hooks, while we want to
> hide some State-specific methods (Param, PreValue, Run). Thus it is
> high time to introduce a new State type for test hooks.
> 
> This is an API incompatible change. No functional change expected.
> 
> BUG=chromium:965703
> BUG=chromium:1103118
> TEST=fast_build.sh -T
> 
> Cq-Depend: chromium:2286973
> Change-Id: Ia97839d0d775b9a2147542f0147e3d5c601d7c57
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast/+/2287015
> Commit-Queue: Shuhei Takahashi <nya@chromium.org>
> Tested-by: Shuhei Takahashi <nya@chromium.org>
> Reviewed-by: Keigo Oka <oka@chromium.org>

Bug: chromium:965703, chromium:1103118
Change-Id: I0c62a41eb1eb4dea9f650e8366b9acef43822e51